#!/bin/bash
# Quick Start Guide สำหรับ IMX500 Camera System

echo "========================================="
echo "🎥 IMX500 Camera System - Quick Start"
echo "========================================="
echo ""
echo "✅ Pi Server กำลังทำงานที่:"
echo "   🌐 http://172.20.10.2:5000"
echo ""
echo "📋 ขั้นตอนถัดไป:"
echo ""
echo "1️⃣  เปิด Terminal ใหม่"
echo "2️⃣  รันคำสั่ง:"
echo "    cd /home/admin/Desktop/kiosk\ promax/kiosk"
echo "    npm run dev"
echo ""
echo "3️⃣  เปิดเบราว์เซอร์ไปที่:"
echo "    http://localhost:5173"
echo ""
echo "========================================="
echo "🎬 Features:"
echo "   ✓ Face Detection (IMX500 AI)"
echo "   ✓ Age Estimation"
echo "   ✓ Gender Recognition"
echo "   ✓ Emotion Analysis"
echo "   ✓ LED Strip Control"
echo "   ✓ Proximity Sensor"
echo "========================================="
echo ""
echo "📖 อ่านเพิ่มเติม:"
echo "   - IMX500_SETUP.md"
echo "   - FACE_DETECTION_SETUP.md"
echo ""
echo "🛑 หยุด Pi Server: pkill -f app_imx500.py"
echo ""
